config/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve
from django.conf import settings
from django.conf.urls.static import static

# from . import views

handler404 = 'config.views.page_not_found_view'
handler500 = 'config.views.error_view'
handler403 = 'config.views.permission_denied_view'
handler400 = 'config.views.bad_request_view'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('users.urls')),
    path('', include('trails.urls')),
    re_path(r'^uploads/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    # path('errortest', views.errortest)
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

trails/urls.py
from django.urls import path
from . import views

app_name = 'trails'
urlpatterns = [
    path('', views.home, name = 'home'),
    path('trail/<slug:slug>/processing', views.process_upload, name = 'process_upload'),
    path('trail/<slug:slug>', views.view_trail, name = 'view_trail'),
    path('new', views.new_trail, name = 'new_trail'),
    path('trail/<slug:slug>/edit', views.edit_trail, name = 'edit_trail'),
    path('trail/<slug:slug>/delete', views.delete_trail, name = 'delete_trail'),
    path('trail/<slug:slug>/get_trail_assets', views.get_trail_assets, name = 'get_trail_assets'),
    path('trail/<slug:slug>/get_user_trails', views.get_user_trails, name = 'get_user_trails'),
    path('trail/<slug:slug>/add_trail_photos', views.add_trail_photos, name = 'add_trail_photos'),
    path('trail/<slug:slug>/delete_trail_photo/<int:id>', views.delete_trail_photo, name = 'delete_trail_photo'),
    path('trail/<slug:slug>/edit_trail_photo/<int:id>', views.edit_trail_photo, name = 'edit_trail_photo'),
    path('trail/<slug:slug>/add_trail_comment', views.add_trail_comment, name = 'add_trail_comment'),
    path('trail/<slug:slug>/delete_trail_comment/<int:id>', views.delete_trail_comment, name = 'delete_trail_comment'),
    path('get_all_trails', views.get_all_trails, name = 'get_all_trails'),
    # below are for presentation
    path('about-1', views.about_1),
    path('about-2', views.about_2),
    path('about-3', views.about_3),
    path('about-4', views.about_4),
]

users/urls.py
from django.urls import path

from . import views

app_name = 'users'
urlpatterns = [
    path('login/', views.login_user, name='login_user'),
    path('logout/', views.logout_user, name='logout_user'),
    path('signup/', views.signup_user, name='signup_user'),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/modern-normalize@1.1.0/modern-normalize.min.css"> -->
	<script src="https://unpkg.com/vue@3"></script>
	<script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js" defer></script>
    <script src="https://kit.fontawesome.com/5e147aea5d.js" crossorigin="anonymous"></script>
    <script src="{% static 'init.js' %}" defer></script>
    <script src="{% static 'script.js' %}" defer></script>
    <title>{% block title_pre %}{% endblock %}{% block title %}TopoTrail{% endblock %}{% block title_post %}{% endblock %}</title>
</head>
<!-- <body id="app" class="blue-grey darken-4 white-text">
    <nav class="blue-grey darken-4" role="navigation"> -->
<body id="app" class="white blue-grey-text text-darken-4 flex-wrapper">
    {% csrf_token %}
    <nav class="white" role="navigation" id="mainnav">
        <div class="nav-wrapper container">
            <a id="logo-container" href="{% url 'trails:home' %}" class="brand-logo center">TopoTrail</a>
            <ul class="right hide-on-med-and-down">
                <li><a class="modal-trigger" href="#modal-search-trails" class="">Search</a></li>
                {% if request.user.is_authenticated %}
                <li><a class="modal-trigger" href="#modal-add-trail">Add Trail</a></li>
                <li><a href="#" onclick="document.getElementById('logout-form').submit();">Logout</a></li>
                <!-- <li><a href="{% url 'users:logout_user' %}">Logout</a></li> -->
                {% else %}
                <li><a class="modal-trigger" href="#modal-login">Login</a></li>
                <li><a class="modal-trigger" href="#modal-signup">Sign Up</a></li>
                {% endif %}
            </ul>
            
            <ul id="nav-mobile" class="sidenav">
                <li><a class="modal-trigger" href="#modal-search-trails">Search</a></li>
                {% if request.user.is_authenticated %}
                <li><a class="modal-trigger" href="#modal-add-trail">Add Trail</a></li>
                <li><a href="#" onclick="document.getElementById('logout-form').submit();">Logout</a></li>
                <!-- <li><a href="{% url 'users:logout_user' %}">Logout</a></li> -->
                {% else %}
                <li><a class="modal-trigger" href="#modal-login">Login</a></li>
                <li><a class="modal-trigger" href="#modal-signup">Sign Up</a></li>
                {% endif %}
            </ul>
            <a href="#" data-target="nav-mobile" class="sidenav-trigger"><i class="material-icons">menu</i></a>
        </div>
        <!-- Logout Form (hidden) -->
        {% if request.user.is_authenticated %}
        <form action="{% url 'users:logout_user' %}" method="POST" id="logout-form">
            {% csrf_token %}
            <input type="hidden" name="next" value="{{ request.path|urlencode }}">
        </form>
        {% endif %}
    </nav>
    <main>
        {% block content %}{% endblock %}
    </main>

    <!-- MODALS -->

    {% block modals %}
    {% endblock %}

    {% if request.user.is_authenticated %}

    <!-- Add Trail Modal -->
    <div id="modal-add-trail" class="modal bottom-sheet">
        <form action="{% url 'trails:new_trail' %}" method="post" enctype="multipart/form-data">
            <div class="modal-content row">
                <h4>Add Trail</h4>
                {% csrf_token %}
                <div class="input-field col s12">
                    <input id="name" name="name" type="text">
                    <label for="name">
                        Trail Name
                    </label>
                </div>
                <div class="input-field col s12">
                    <input id="desc" name="desc" type="text">
                    <label for="desc">
                        Trail Description
                    </label>
                </div>
                <div class="file-field input-field col s6">
                    <div class="waves-effect waves-light btn-small deep-purple lighten-1">
                        <span>Select Trail File</span>
                        <input type="file" id="trail_file" name="trail_file" class="" accept=".geojson,.gpx">
                    </div>
                    <div class="file-path-wrapper">
                        <input class="file-path validate" type="text">
                    </div>
                </div>
                <div class="input-field col s6">
                    <select id="share_future" name="share_future">
                        <option v-for="(value, key) in shareOptions" :value="key" :selected="value == 'private'">[[ value ]]</option>
                    </select>
                    <label for="share_future">Share Settings</label>
                </div>
            </div>
            <div class="modal-footer">
                <button type="submit" class="waves-effect waves-light btn-small light-green darken-1"><i class="material-icons right">send</i>Add Trail</button>
            </div>
        </form>
    </div>

    {% else %}

    <!-- Login Modal -->
    <div id="modal-login" class="modal bottom-sheet">
        <form action="{% url 'users:login_user' %}" method="POST" class="">
            <div class="modal-content">
                <h4>Login</h4>
                {% csrf_token %}
                <input type="hidden" name="next" value="{{ request.path|urlencode }}">
                <div class="input-field">
                    <input type="text" id="username" name="username" class="">
                    <label for="username">
                        Username
                    </label>
                </div>
                <div class="input-field">
                    <input type="password" id="password" name="password" class="">
                    <label for="password">
                        Password
                    </label>
                </div>
            </div>
            <div class="modal-footer">
                <button type="submit" class="modal-close waves-effect waves-light btn-small light-green darken-1"><i class="material-icons right">send</i>Login</button>
            </div>
        </form>
    </div>

    <!-- Signup Modal -->
    <div id="modal-signup" class="modal bottom-sheet">
        <form action="{% url 'users:signup_user' %}" method="POST" class="">
            <div class="modal-content">
                <h4>Sign Up</h4>
                {% csrf_token %}
                <input type="hidden" name="next" value="{{ request.path|urlencode }}">
                <div class="input-field">
                    <input type="text" id="username" name="username" class="">
                    <label for="username">
                        Username
                    </label>
                </div>
                <div class="input-field">
                    <input type="email" id="email" name="email" class="">
                    <label for="email">
                        Email
                    </label>
                </div>
                <div class="input-field">
                    <input type="password" id="password1" name="password1" class="">
                    <label for="password1">
                        Password
                    </label>
                </div>
                <div class="input-field">
                    <input type="password" id="password2" name="password2" class="">
                    <label for="password2">
                        Confirm password
                    </label>
                </div>
            </div>
            <div class="modal-footer">
                <button type="submit" class="modal-close waves-effect waves-light btn-small light-green darken-1"><i class="material-icons right">send</i>Sign Up</button>
            </div>
        </form>
    </div>
    {% endif %}
    <!-- Modal Structure -->
    <div id="modal-search-trails" class="modal modal-fixed-footer">
        <div class="modal-content">
            <h4>Search Trails</h4>
            <p>Search all trails owned by you or publicly shared.</p>
            <div class="input-field">
                <input name ="search" id="search-trails" type="text" v-model="currentSearchTerm" @keyup="searchAllTrails" data-length="100">
                <label for="search">
                    <i class="material-icons left">search</i>
                </label>
            </div>
            <ul>
                <li v-for="trail in currentSearchResults">
                    <a :href="trail.slug">[[ trail.name ]]</a> - <em>added [[ new Date(trail.timestamp).toLocaleDateString() ]] by [[ trail.upload_user ]]</em>
                </li>
            </ul>
        </div>
        <div class="modal-footer">
            <a href="#!" class="modal-close waves-effect waves-light btn-small light-green darken-1">Close</a>
        </div>
    </div>
    <!-- END MODALS -->
    <footer>
        &copy; 2022 <a href="https://www.iammattwalsh.com/">Matt Walsh</a> - <a href="https://github.com/MattDWalsh/TopoTrail"><i class="fa-brands fa-github-square larger-icon"></i> view on github</a>
    </footer>
</body>
</html>

templates/basepres.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/modern-normalize@1.1.0/modern-normalize.min.css"> -->
	<script src="https://unpkg.com/vue@3"></script>
	<script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js" defer></script>
    <script src="https://kit.fontawesome.com/5e147aea5d.js" crossorigin="anonymous"></script>
    <script src="{% static 'init.js' %}" defer></script>
    <script src="{% static 'script.js' %}" defer></script>
    <title>{% block title_pre %}{% endblock %}{% block title %}TopoTrail{% endblock %}{% block title_post %}{% endblock %}</title>
</head>
<!-- <body id="app" class="blue-grey darken-4 white-text">
    <nav class="blue-grey darken-4" role="navigation"> -->
<body id="app" class="white blue-grey-text text-darken-4 flex-wrapper">
    <main>
        {% block content %}{% endblock %}
    </main>
</body>
</html>